internal_method_name -> _internal_method_name

diff --git a/functions/batch-handbrake b/functions/batch-handbrake
--- a/functions/batch-handbrake
+++ b/functions/batch-handbrake
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-usage() {
+_usage() {
     echo "$( basename $0 ): usage"
     echo "  -i --input      directory in which to scan"
     echo "  -x --extension   file extension for output"
@@ -19,7 +19,7 @@ usage() {
 # Returns:
 #   The executable's path
 #######################################
-get_handbrake_cli() {
+_get_handbrake_cli() {
     if hash HandBrakeCLI 2>/dev/null; then
         echo "HandBrakeCLI"
     elif [ -d "/usr/local/Cellar/handbrake" ]; then
@@ -40,8 +40,8 @@ get_handbrake_cli() {
 # Returns:
 #   None
 #######################################
-convert() {
-    executable=$( get_handbrake_cli ) || { echo " "; echo "ERROR: HandBrakeCLI not found"; exit 1; }
+_convert() {
+    executable=$( _get_handbrake_cli ) || { echo " "; echo "ERROR: HandBrakeCLI not found"; exit 1; }
     for f in $1; do
         output=${f%.*}.$2
 
@@ -59,14 +59,14 @@ while [ "$1" != "" ]; do
         -x | --ext )        shift
                             extension=$1
                             ;;
-        -h | --help )       usage 0
+        -h | --help )       _usage 0
                             ;;
-        * )                 usage 1
+        * )                 _usage 1
     esac
     shift
 done
 
-[[ -z $input || -z $extension ]] && { usage 1; }
+[[ -z $input || -z $extension ]] && { _usage 1; }
 
 echo "About to encode these files:"
 ls $input
@@ -75,7 +75,7 @@ echo " "
 
 read -r -p "Are you sure? [y/N] " response
 case "$response" in
-    [yY])   convert "$input" $extension
+    [yY])   _convert "$input" $extension
             ;;
     *)      exit 0
             ;;
